
modLoader="javafml" #mandatory

loaderVersion="[34,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

[[mods]] #mandatory

modId="maidensmaterials" #mandatory

version="${file.jarVersion}" #mandatory

displayName="Maiden's Marvelous Materials" #mandatory







description='''
'''

[[dependencies.maidensmaterials]] #optional

    modId="forge" #mandatory

    mandatory=true #mandatory

    versionRange="[34,)" #mandatory

    ordering="NONE"

    side="BOTH"

[[dependencies.maidensmaterials]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
